### ISSUE TITLE
Unlocking The Security Setting Of Mobile Hotspot In Win10

### ISSUE THREAD

**Issue by ghost** [antoniotejada/WiFiDirectLegacyAP#2]
Windows 10 has mobile hotspot supported and it works completely well even if the laptop/PC does not support hostednetwork. Given that, my goal is to have full control over the mobile hotspot feature including the DOT11_AUTH and the DOT11_CIPHER on a security setting I want. How's this possible?

**Comment by antoniotejada** [comment]
This project is just a port of Microsoft's [WiFiDirectLegacyAP example](https://github.com/microsoft/windows-classic-samples/tree/main/Samples/WiFiDirectLegacyAP), I won't be doing anything outside of what that example does (unless someone finds out it's just a couple of lines of code). 

Closing won't fix.
